---
title: '"Husky Check-In" Sample Code'
author: "Courtney Berger Levinson"
date: "May 30, 2024"
output:
  word_document:
    toc: yes
    toc_depth: '3'
params:
  use_campus: Seattle
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library('tidyverse')  ## Facilitates creating, analyzing, and displaying tidy data
library('readxl')     ## Imports Excel files into R
library('openxlsx')   ## Facilitates reading, writing, and editing .xlsx (Microsoft Excel) files
```

```{r data, echo=FALSE}
# 0. Set working drive (if working solo)       
#    More info on setwd and pitfalls:   (https://swcarpentry.github.io/r-novice-inflammation/06-best-practices-R.html#be-careful-when-using-setwd)
     setwd("C:/Users/cberglev/OneDrive - UW/AIR Forum 2024/")

# 1. Import data
     dat  <- read_excel("C:/Users/cberglev/OneDrive - UW/AIR Forum 2024/20240530_AIRForum_BergerLevinson_FakeData.xlsx", sheet = "dat")

# 2.Cleaning (This isn't an exhaustive list of examples)
## 2.1 Convert character variables to factor 
### 2.1.1 Create a list of string -> factor variables
          chars <- c("variable1","variable2")
### 2.1.2. Convert
           dat[,chars] <- lapply(dat[,chars],factor)
## 2.2 Re-code vars where print order is important
       dat$variable1<- factor(dat$variable1, levels = c("Choice 1",
                                                        "Choice 2",
                                                        "Choice 3"))
## 2.4 Save copy of "clean" dataset
       # write.xlsx(dat,"BergerLevinson_FakeData_CLEAN.xlsx",
       #             sheetName = "dat", overwrite = TRUE)
       # save(dat, file = "BergerLevinson_FakeData.xlsx_CLEAN.Rdata")
```
\newpage
# `r params$use_campus` Results
```{r campus, echo=FALSE}
# Subset data for the identified campus (see header)
dat_c <- subset(dat, Campus == params$use_campus)
```
## Subsection 1
### Sample table construction: Variable 1, by variable 2 
```{r sched, echo=FALSE}
# Create table: Variable 1, by variable 2  
v1Xv2 <- table(dat_c$variable1,
               dat_c$variable2)
#Rename "sum" function so that the table column reads "Total" instead
Total <- sum

# Generate student schedule type percentages, by level
v1Xv2_p <- v1Xv2 %>%
  prop.table(margin = 2) %>% {.* 100} %>%  round(digits=1) %>%
  addmargins(margin=1, FUN = Total)

# Print proportions of student study modality/schedule type
knitr::kable(v1Xv2_p)

# Clean up environment
rm(v1Xv2, v1Xv2_p)
```